### PR TITLE
Refactored JS & HTML files, added buy functionality 

### PR DESCRIPTION
**Pull request by doublem1nt**
Added Features:
(1) URL for Buy Book added to each Book Image.
(2) Added Random NYT Best Seller Suggestion to Front Page on Load
(3) Added Pseudo Code comments
(4) Basic README set up

### CODE REVIEW

**Comment by NickLynnJohnson** [comment]
Hi @doublem1nt can you change:
Changed Assitant to Assistant on index.html
Removed extra space before colon on "Search by title or author to find your next book club choice :" on index.html
Changed disigned to"designed" on ReadMe

**Comment by doublem1nt** [comment]
Updated per Nick's Comments.

**Comment by cnix273** [comment]
Looking good!

**Review by cnix273 — APPROVED** [review]
Looking good!

**Pull request merged**
